// SPDX-License-Identifier: GPL-3.0-only

//! A C++ binding for [`prolink`], generated by [`cxx`].
//!
//! Built for Mixxx, whose Pro DJ Link support is being replaced by calls into
//! this library, and shaped by that: the C++ side is meant to be a thin shell
//! that renders, so **everything here hands over state that is ready to
//! display** rather than parts a caller has to reassemble. There is no packet,
//! no socket and no parsing in this API.
//!
//! # Why `cxx` and not a C ABI
//!
//! A hand-written C header has to be kept in step with the Rust by hand, and
//! the failure mode when it is not is a caller's stack corrupted at run time,
//! on a machine the author does not have. `cxx` generates both sides from this
//! one file, so the same mistake is a compile error in both languages — and
//! `String` and `Vec` cross as `rust::String` and `rust::Vec` rather than as
//! fixed-size buffers with a length convention.
//!
//! Nothing on the C++ side of this boundary is `unsafe`, and nothing it
//! receives needs freeing.
//!
//! # Two rules the surface follows
//!
//! **Events are drained, never pushed.** A callback would be invoked from a
//! tokio worker thread, which for a Qt host means every handler has to be
//! thread-safe and re-entrant, and a slow one stalls the network. Instead
//! `drain_events` returns everything queued since the last call, on the
//! caller's own thread, from a timer or an idle handler. Back-pressure is
//! bounded rather than unbounded: `Event::dropped` says how much was missed.
//!
//! **Absent numbers are negative, never zero.** A host drawing a tempo has to
//! tell "not playing" from "0.00 BPM", and zero cannot. `cxx` has no `Option`
//! in a shared struct, so the convention is explicit and applied everywhere:
//! `-1.0` means "no value", not a value of minus one.
//!
//! # Example
//!
//! ```cpp
//! #include "prolink-cxx/src/lib.rs.h"
//!
//! auto session = prolink::open(prolink::default_config());
//!
//! // From a UI timer, on your own thread:
//! for (const prolink::Event& event : session->drain_events()) {
//!     if (event.kind == prolink::EventKind::Beat) { /* ... */ }
//! }
//!
//! for (const prolink::Player& player : session->players()) {
//!     if (player.is_master) {
//!         meter->setPhase(player.bar_phase);
//!     }
//! }
//! ```

mod browse;
mod convert;
mod pdb;
mod serve;
mod session;

pub use session::Session;

/// The shared vocabulary, and the entry points.
///
/// `cxx` generates the C++ declarations for everything in here, so a field
/// added on one side cannot go missing on the other: it is a compile error in
/// both languages rather than a layout mismatch at run time.
#[allow(
    unsafe_code,
    reason = "the bridge macro expands to the extern declarations that make \
              the two languages agree on layout and lifetime, and those cannot \
              be written safely. Nothing hand-written in this crate is unsafe, \
              which is the whole reason for choosing cxx over a C ABI."
)]
#[cxx::bridge(namespace = "prolink")]
pub mod ffi {
    /// What a device says it is.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum DeviceKind {
        /// Anything we have no name for.
        Unknown,
        /// A player.
        Cdj,
        /// A mixer.
        Mixer,
        /// rekordbox on a computer, and also the CDJ-3000.
        Rekordbox,
    }

    /// Which slot media is in.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum Slot {
        /// Nothing.
        None,
        /// The CD drive.
        Cd,
        /// The SD card.
        Sd,
        /// The USB slot.
        Usb,
        /// Another player's media, over LINK.
        Rekordbox,
    }

    /// What a platter is doing.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum PlayState {
        /// Nothing loaded.
        NoTrack,
        /// Loading.
        Loading,
        /// Playing.
        Playing,
        /// Playing inside a loop.
        Looping,
        /// Paused.
        Paused,
        /// Stopped at the cue point.
        Cued,
        /// Playing from the cue point while the button is held.
        CuePlay,
        /// Searching.
        Searching,
        /// Spun down.
        SpunDown,
        /// The medium went away mid-play and the deck is looping its buffer.
        Emergency,
        /// A value this library has never seen on the wire.
        Other,
    }

    /// What happened.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum EventKind {
        /// A device appeared.
        DeviceFound,
        /// A device's details changed.
        DeviceChanged,
        /// A device stopped sending keep-alives.
        DeviceLost,
        /// A player started a beat. `beat_in_bar` says which.
        Beat,
        /// A player's status changed: what is loaded, or what it is doing.
        PlayerChanged,
        /// Tempo master moved. `device` is the new master, or zero for nobody.
        TempoMaster,
        /// A player stopped sending beats.
        Stopped,
        /// A transfer advanced. `transfer`, `done` and `total` are set.
        TransferProgress,
        /// A transfer finished. `ok` says whether it succeeded, `detail`
        /// carries the reason when it did not, and `path` is where it was
        /// written.
        TransferDone,
        /// A player described one of its slots: volume name and counts.
        ///
        /// A deck sends this once, when it first browses a slot, so a host
        /// that only polls `media()` may wait a long time for it (F37).
        MediaInfo,
    }

    /// How to start a session.
    #[derive(Debug, Clone)]
    struct Config {
        /// The interface to use, or empty to choose one.
        ///
        /// Choosing automatically prefers a link-local address, which is what
        /// a DJ network always is; on a machine with two candidates it is a
        /// coin toss, so a host with a settings screen should name one.
        interface: String,

        /// Whether to announce as a virtual CDJ.
        ///
        /// **Off means the loaded track, the play state and the tempo master
        /// are never populated**, because a player unicasts status to peers
        /// that have announced themselves and to nobody else (F21). Tempo and
        /// beat phase still arrive, since beats are broadcast.
        announce: bool,
    }

    /// A network interface that could carry Pro DJ Link traffic.
    #[derive(Debug, Clone)]
    struct NetworkInterface {
        /// The system's name for it.
        name: String,
        /// Its IPv4 address.
        address: String,
        /// Its broadcast address.
        broadcast: String,
        /// Whether the address is link-local, which a DJ network's always is.
        ///
        /// A host choosing automatically should prefer these: a CDJ
        /// self-assigns in `169.254.0.0/16` after DHCP fails (F8).
        is_link_local: bool,
    }

    /// A device on the network.
    #[derive(Debug, Clone)]
    struct Device {
        /// 1–6 for a player, higher for other things.
        number: u8,
        /// What kind of device it says it is.
        kind: DeviceKind,
        /// Whether it is a player, and so something that can be browsed.
        is_player: bool,
        /// Whether it is still sending keep-alives.
        online: bool,
        /// Its hardware address, as `00:11:22:33:44:55`.
        mac: String,
        /// Its name. `CDJ-2000nexus` and the like.
        name: String,
        /// Its IPv4 address.
        address: String,
        /// Milliseconds since its last keep-alive.
        last_seen_ms: u64,
    }

    /// What one player is doing, as a host would render it.
    ///
    /// The fields that need a status packet — the loaded track, the play
    /// state, the tempo master — are populated only when the session
    /// announced itself (F21). `has_status` says whether they mean anything,
    /// so a host never draws a confident zero it was never told.
    #[derive(Debug, Clone)]
    struct Player {
        /// The player's number.
        number: u8,
        /// Its name.
        name: String,

        /// Whether the status fields below mean anything.
        has_status: bool,
        /// Whether it is sending beats, and so playing a rekordbox track.
        is_beating: bool,

        /// The tempo actually playing: the track's BPM with pitch applied.
        /// Negative when unknown.
        effective_bpm: f64,
        /// The track's own BPM, before pitch. Negative when unknown.
        track_bpm: f64,
        /// The pitch fader as a percentage, zero at centre.
        ///
        /// **Not the fader position while `is_synced`**: a synced deck slews
        /// this to hold its effective tempo equal to the master's (F51).
        pitch_percent: f64,

        /// Position within the current beat, `0.0` on the beat. Negative when
        /// the player is not beating or the estimate has gone stale.
        beat_phase: f64,
        /// Position within the four-beat bar, `0.0` on the downbeat. Negative
        /// when unknown.
        bar_phase: f64,
        /// Which beat of the bar, 1–4. Zero when the player has no bar to be
        /// in, which is what an unanalysed track reports.
        beat_in_bar: u8,

        /// Whether this player holds tempo master.
        is_master: bool,
        /// Whether SYNC is lit.
        is_synced: bool,
        /// The device it is handing master to, or zero.
        ///
        /// Non-zero for only the one or two packets of a handoff, during which
        /// **both** decks report themselves master; a host that ignores this
        /// will see mastership flicker (F52).
        yielding_to: u8,

        /// What the platter is doing.
        play_state: PlayState,
        /// The loaded track's row id, or zero.
        track_id: u32,
        /// Which player the loaded track came from.
        track_source_player: u8,
        /// Which of that player's slots.
        track_source_slot: Slot,
    }

    /// A row in a browse menu: a track, an artist, an album, a category.
    #[derive(Debug, Clone)]
    struct Row {
        /// What the row names — a track id in a track list, an artist id in an
        /// artist list. What to pass back when the user opens it.
        id: u32,
        /// The first line: a title, a name, a category label.
        label: String,
        /// The second line, which the sort chooses: the artist under a title,
        /// the tempo under a BPM sort. Empty when the sort is numeric.
        detail: String,
        /// The raw item type, so a host can tell a track row from a category
        /// row without matching on the label.
        item_type: u32,
        /// The artwork to fetch for this row, or zero.
        artwork_id: u32,
        /// Its 1-based position inside a playlist, or its track number.
        position: u32,
        /// Whether this row is the track the browsing deck has loaded.
        is_loaded: bool,
        /// Whether this row is in the deck's tag list.
        is_tagged: bool,
    }

    /// Everything a deck will tell us about one track.
    #[derive(Debug, Clone)]
    struct Metadata {
        /// The track's row id.
        id: u32,
        /// Its title.
        title: String,
        /// Its artist.
        artist: String,
        /// Its album.
        album: String,
        /// Its genre.
        genre: String,
        /// Its musical key, as the medium spells it — Camelot on one export,
        /// classical on another, because that is a rekordbox setting.
        key: String,
        /// Its record label.
        label: String,
        /// Its colour tag.
        colour: String,
        /// The DJ comment.
        comment: String,
        /// When it was added, as `2025-06-24`.
        date_added: String,
        /// How long it runs, in seconds.
        duration_seconds: u32,
        /// Its tempo in hundredths of a BPM, before any pitch fader.
        tempo_centibpm: u32,
        /// Its star rating.
        rating: u32,
        /// Its bitrate in kbps.
        bitrate: u32,
        /// The artwork to fetch, or zero.
        artwork_id: u32,
    }

    /// What one of a player's slots holds.
    #[derive(Debug, Clone)]
    struct MediaInfo {
        /// Which player.
        device: u8,
        /// Which slot.
        slot: Slot,
        /// Whether a medium is present and mounted.
        has_media: bool,
        /// The volume name, empty until the player has described the slot.
        volume_name: String,
        /// When the export was written, as `2025-06-24`. Empty until known.
        created: String,
        /// How many tracks it holds. Zero until known.
        track_count: u32,
        /// How many playlists. Zero until known.
        playlist_count: u32,
    }

    /// How to serve local media to real players.
    #[derive(Debug, Clone)]
    struct ServeConfig {
        /// The interface to use, or empty to choose one.
        interface: String,
        /// The medium to present in the USB slot, or empty for none.
        usb_path: String,
        /// The medium to present in the SD slot, or empty for none.
        ///
        /// A second USB stick shown as an SD card is exactly what a CDJ
        /// expects to see.
        sd_path: String,
    }

    /// One of our own slots, as we offer it.
    #[derive(Debug, Clone)]
    struct ServedSlot {
        /// Which slot we present it in.
        slot: Slot,
        /// The volume name a deck shows.
        volume_name: String,
        /// Where it came from on this machine.
        local_path: String,
        /// The NFS export path a deck mounts.
        export_path: String,
        /// How many tracks it holds.
        track_count: u32,
        /// How many playlists.
        playlist_count: u32,
    }

    /// A player that has taken a track off our media.
    #[derive(Debug, Clone)]
    struct ServeConsumer {
        /// Which player.
        device_number: u8,
        /// Its name.
        device_name: String,
        /// Its address.
        address: String,
        /// Which of our slots it took the track from.
        slot: Slot,
        /// The track's row id.
        track_id: u32,
        /// Whether it is playing right now.
        playing: bool,
    }

    /// What a running server is doing.
    #[derive(Debug, Clone)]
    struct ServeStatus {
        /// Whether we hold a player number, without which nothing else here
        /// matters: a deck validates it in every dbserver request (F45).
        active: bool,
        /// The number we hold, 1–4.
        device_number: u8,
        /// The address we serve from.
        address: String,
        /// The interface we serve on.
        interface: String,
        /// Where the portmapper is listening.
        ///
        /// **Must be 111.** With nothing there a deck retries `GETPORT` once a
        /// second for ever rather than falling back to the well-known ports,
        /// and never reaches the dbserver at all (F46).
        portmap_port: u16,
        /// Where mountd is listening.
        mount_port: u16,
        /// Where nfsd is listening.
        nfs_port: u16,
        /// Where the dbserver is listening.
        dbserver_port: u16,
        /// Whether a real player can actually find us — the portmapper is on
        /// 111 and we hold a browsable number.
        is_discoverable: bool,
        /// The media we are offering.
        media: Vec<ServedSlot>,
        /// The players reading from us, and what each has loaded.
        consumers: Vec<ServeConsumer>,
    }

    /// One track, as `export.pdb` stores it.
    ///
    /// The names are resolved as well as their row ids given: a host that only
    /// wants to show a track never has to join anything, and one building a
    /// browse tree still can.
    #[derive(Debug, Clone)]
    struct PdbTrack {
        /// The row id, which is what every other request names a track by.
        id: u32,
        /// The track's title.
        title: String,
        /// Its artist, resolved from the artist table.
        artist: String,
        /// Its album.
        album: String,
        /// Its genre.
        genre: String,
        /// Its musical key, as the medium spells it.
        key: String,
        /// Its record label.
        label: String,
        /// Its colour tag.
        color: String,
        /// The DJ comment.
        comment: String,
        /// The path on the medium, with a leading slash, exactly as the
        /// database stores it — which is what a fetch takes verbatim.
        file_path: String,
        /// The `.DAT` beside it, holding the beat grid and waveforms.
        analyze_path: String,
        /// The artwork file on the medium, if it has one.
        artwork_path: String,
        /// When it was added, as `2025-06-24`.
        date_added: String,
        /// Its release year, or zero.
        year: u32,
        /// How long it runs.
        duration_seconds: u32,
        /// In kbps.
        bitrate: u32,
        /// Hundredths of a BPM, so 145.00 is 14500.
        tempo_centibpm: u32,
        /// Its star rating.
        rating: u32,
        /// The artwork to fetch, or zero.
        artwork_id: u32,
        /// In Hz.
        sample_rate: u32,
        /// In bytes.
        file_size: u32,
        /// Its number within its album.
        track_number: u32,
        /// Its disc, for a multi-disc album.
        disc_number: u32,
        /// How many times a deck has played it.
        play_count: u32,
        /// The container byte, which is what a deck uses to decide how to
        /// decode the file.
        file_type: u32,
        /// The artist's row id, for a browse tree.
        artist_id: u32,
        /// The album's row id.
        album_id: u32,
        /// The genre's row id.
        genre_id: u32,
        /// The key's row id. Per-medium, not a canonical index.
        key_id: u32,
        /// The label's row id.
        label_id: u32,
        /// The colour's palette index.
        color_id: u32,
    }

    /// A playlist, or a folder of them.
    #[derive(Debug, Clone)]
    struct PdbPlaylist {
        /// Its row id.
        id: u32,
        /// The folder it sits in, or zero at the top level.
        parent_id: u32,
        /// Where it sorts among its siblings.
        sort_order: u32,
        /// Its name.
        name: String,
        /// Whether it holds other playlists rather than tracks.
        is_folder: bool,
        /// Empty for a folder, and in the DJ's own order for a playlist.
        track_ids: Vec<u32>,
    }

    /// A row of one of the lookup tables, for building a browse tree.
    #[derive(Debug, Clone)]
    struct PdbNamed {
        /// The row id a track refers to.
        id: u32,
        /// What to show for it.
        name: String,
    }

    /// Everything read out of one `export.pdb`.
    #[derive(Debug, Clone)]
    struct PdbContents {
        /// Whether it parsed. On false the rest is empty and `error` says why.
        ok: bool,
        /// Why it did not parse. Empty when `ok`.
        error: String,
        /// Every track on the medium.
        tracks: Vec<PdbTrack>,
        /// Every playlist and folder.
        playlists: Vec<PdbPlaylist>,
        /// The artist table.
        artists: Vec<PdbNamed>,
        /// The album table.
        albums: Vec<PdbNamed>,
        /// The genre table.
        genres: Vec<PdbNamed>,
        /// The key table. Its ids are per-medium.
        keys: Vec<PdbNamed>,
        /// The record-label table.
        labels: Vec<PdbNamed>,
        /// The colour palette.
        colors: Vec<PdbNamed>,
        /// The artwork table: id to file path.
        artwork: Vec<PdbNamed>,
    }

    /// One thing that happened.
    ///
    /// Flat rather than a variant per kind, because C++ has no cheap sum type
    /// and a host switches on `kind` and reads the two or three fields that
    /// kind gives meaning to.
    #[derive(Debug, Clone)]
    struct Event {
        /// What happened.
        kind: EventKind,
        /// Which device, or zero where the event is not about one.
        device: u8,
        /// Which beat of the bar, for `Beat`. Zero otherwise.
        beat_in_bar: u8,
        /// How many events were discarded before this one because the host
        /// stopped draining.
        ///
        /// Non-zero means state was missed, and the host should re-read
        /// `devices()` and `players()` rather than trust its running picture.
        dropped: u32,

        /// Which transfer, for the two transfer kinds. Zero otherwise.
        transfer: u32,
        /// Bytes transferred so far, contiguous from the start of the file —
        /// never a running total that could exceed what is safely assembled.
        done: u64,
        /// Bytes the file holds. Zero if not yet known.
        total: u64,
        /// For `TransferDone`, whether it succeeded.
        ok: bool,
        /// For a failed `TransferDone`, why. Empty otherwise.
        detail: String,
        /// For `TransferDone`, the local path it was written to.
        ///
        /// Carried as well as the id, because a host that keyed its own state
        /// on the path it asked for should not have to keep an id table to get
        /// back to it.
        path: String,
        /// For `MediaInfo`, which slot was described.
        slot: Slot,
    }

    extern "Rust" {
        /// A running session: sockets, timers, and the state they maintain.
        type Session;

        /// The interfaces that could carry Pro DJ Link traffic.
        fn interfaces() -> Vec<NetworkInterface>;

        /// A config that chooses an interface and announces.
        fn default_config() -> Config;

        /// Read a rekordbox `export.pdb` off disk.
        ///
        /// Never throws: a database that does not parse comes back with `ok`
        /// false and `error` set, because a host that has just pulled several
        /// megabytes over NFS wants to show the user why rather than unwind.
        fn read_pdb(path: &str) -> PdbContents;

        /// Start a session. Throws on failure, with the reason.
        fn open(config: &Config) -> Result<Box<Session>>;

        /// The number we announced as, or zero if we did not announce.
        fn device_number(self: &Session) -> u8;

        /// Everyone on the network, as of now.
        fn devices(self: &Session) -> Vec<Device>;

        /// What every player is doing, as of now.
        fn players(self: &Session) -> Vec<Player>;

        /// Everything that has happened since the last call.
        ///
        /// Empty is the normal case. Call it from a timer; nothing is ever
        /// pushed from a network thread.
        fn drain_events(self: &Session) -> Vec<Event>;

        /// Fetch one file from a player's medium into `local_path`.
        ///
        /// Returns a transfer id. Progress arrives as `TransferProgress`
        /// events carrying that id, and exactly one `TransferDone` ends it.
        ///
        /// `remote_path` is taken verbatim from `export.pdb`, which stores
        /// paths relative to the medium root with a leading slash.
        ///
        /// **Nothing partial is ever written.** The file is assembled and
        /// written once, because a truncated `export.pdb` parses far enough to
        /// look plausible and then yields a library missing its last few
        /// hundred tracks.
        fn fetch_file(
            self: &Session,
            device_number: u8,
            slot: Slot,
            remote_path: &str,
            local_path: &str,
        ) -> Result<u32>;

        /// Whether the sockets are up and we are hearing the network.
        fn is_listening(self: &Session) -> bool;

        /// The last thing that went wrong, or empty. For a status line.
        fn last_error(self: &Session) -> String;

        /// Forget every device and re-learn the network.
        ///
        /// A host offers this when a user has re-cabled the rig: a deck that
        /// vanished without a keep-alive is otherwise held for the full
        /// timeout.
        fn refresh(self: &mut Session);

        /// What every player's slots hold, as of now.
        ///
        /// A slot a player has not yet described comes back with
        /// `has_media` true and the counts zero: the presence is published in
        /// every status packet, the description only when a deck first asks
        /// (F20, F37).
        fn media(self: &Session) -> Vec<MediaInfo>;

        /// The root menu of a player's slot, as its LINK button shows it.
        ///
        /// **Blocks on the network, and claims a browsable device number the
        /// first time.** Call it off the UI thread; a dbserver request needs a
        /// number in 1–4, which contends with the decks for one (F45).
        fn root_menu(self: &mut Session, device_number: u8, slot: Slot) -> Result<Vec<Row>>;

        /// Every track on a player's slot, under the given sort.
        ///
        /// Blocks; see `root_menu`. `sort` is zero for the default, which is
        /// by title.
        fn track_rows(
            self: &mut Session,
            device_number: u8,
            slot: Slot,
            sort: u32,
        ) -> Result<Vec<Row>>;

        /// Search a player's slot, the way its on-screen keyboard does.
        ///
        /// Blocks; see `root_menu`. The term is upper-cased on the way out,
        /// because a deck's own keyboard has no lower case and its dbserver is
        /// case-sensitive (F44).
        fn search(
            self: &mut Session,
            device_number: u8,
            slot: Slot,
            term: &str,
        ) -> Result<Vec<Row>>;

        /// Everything a player will say about one track.
        ///
        /// Blocks; see `root_menu`.
        fn metadata(
            self: &mut Session,
            device_number: u8,
            slot: Slot,
            track_id: u32,
        ) -> Result<Metadata>;

        /// Fetch a track's artwork and write it to `local_path`.
        ///
        /// Blocks; see `root_menu`. Artwork is small and comes over the
        /// dbserver connection rather than NFS, so it is not worth the event
        /// machinery a file transfer needs.
        fn fetch_artwork(
            self: &mut Session,
            device_number: u8,
            slot: Slot,
            artwork_id: u32,
            local_path: &str,
        ) -> Result<()>;

        /// The device number a MAC currently holds, or zero.
        ///
        /// A player's *number* can be reassigned while its MAC cannot, so a
        /// host that keeps a request across time should hold the MAC and
        /// resolve it here rather than cache the number.
        fn device_number_of(self: &Session, mac: &str) -> u8;

        /// Fetch a player's `export.pdb`, the database a browse is built from.
        ///
        /// The same contract as `fetch_file`; this is the path a host does not
        /// have to know.
        fn fetch_database(
            self: &Session,
            device_number: u8,
            slot: Slot,
            local_path: &str,
        ) -> Result<u32>;
    }

    extern "Rust" {
        /// A running server: our media, offered to real players.
        type Server;

        /// Start serving. Throws on failure, with the reason.
        ///
        /// **Needs UDP/111**, which is privileged: run as root, or on Linux
        /// set `net.ipv4.ip_unprivileged_port_start=111`. Without it a deck
        /// retries `GETPORT` once a second for ever and never finds us (F46).
        fn serve(config: &ServeConfig) -> Result<Box<Server>>;

        /// What this server is doing.
        fn status(self: &Server) -> ServeStatus;

        /// Stop serving, ejecting the media first.
        ///
        /// Not the same as dropping it. A deck reading our files has a mount
        /// open, and sockets that simply vanish leave it retrying against
        /// nothing; ejecting walks each slot through the unmounting states a
        /// consumer waits for before the slot goes empty (F20).
        fn stop(self: &mut Server);
    }
}

pub use ffi::{
    Config, Device, DeviceKind, Event, EventKind, MediaInfo, Metadata, NetworkInterface,
    PdbContents, PdbNamed, PdbPlaylist, PdbTrack, PlayState, Player, Row, ServeConfig,
    ServeConsumer, ServeStatus, ServedSlot, Slot,
};
pub use serve::{Server, serve};

/// The slot the library receives for one C++ named, for tests.
#[doc(hidden)]
#[must_use]
pub fn slot_back_for_test(slot: Slot) -> prolink_proto::Slot {
    convert::slot_back(slot)
}

/// A `TransferDone` event as the transfer path builds it, for tests.
#[doc(hidden)]
#[must_use]
pub fn transfer_done_for_test(id: u32, path: &str, failure: Option<&str>) -> Event {
    let mut event = convert::plain(EventKind::TransferDone, 0, 0);
    event.transfer = id;
    path.clone_into(&mut event.path);
    if let Some(reason) = failure {
        event.ok = false;
        reason.clone_into(&mut event.detail);
    }
    event
}

/// A player we have heard beats from but no status, for tests.
#[doc(hidden)]
#[must_use]
pub fn empty_player_for_test() -> Player {
    convert::player(&prolink::PlayerState {
        device: prolink::DeviceNumber::ONE,
        name: prolink::DeviceName::default(),
        beat: None,
        status: None,
    })
}

/// One browse row, for tests that cannot reach a deck.
///
/// The two live marks a server puts on a track row are the thing most worth
/// pinning, and a test cannot get one off the network on a build machine.
#[doc(hidden)]
#[must_use]
pub fn row_for_test(item: &prolink_proto::dbserver::MenuItem) -> Row {
    convert::row(item)
}
pub use pdb::read_pdb;
pub use session::{default_config, interfaces, open};
