// SPDX-License-Identifier: GPL-3.0-only

//! A C++ binding for [`prolink`], generated by [`cxx`].
//!
//! Built for Mixxx, whose Pro DJ Link support is being replaced by calls into
//! this library, and shaped by that: the C++ side is meant to be a thin shell
//! that renders, so **everything here hands over state that is ready to
//! display** rather than parts a caller has to reassemble. There is no packet,
//! no socket and no parsing in this API.
//!
//! # Why `cxx` and not a C ABI
//!
//! A hand-written C header has to be kept in step with the Rust by hand, and
//! the failure mode when it is not is a caller's stack corrupted at run time,
//! on a machine the author does not have. `cxx` generates both sides from this
//! one file, so the same mistake is a compile error in both languages — and
//! `String` and `Vec` cross as `rust::String` and `rust::Vec` rather than as
//! fixed-size buffers with a length convention.
//!
//! Nothing on the C++ side of this boundary is `unsafe`, and nothing it
//! receives needs freeing.
//!
//! # Two rules the surface follows
//!
//! **Events are drained, never pushed.** A callback would be invoked from a
//! tokio worker thread, which for a Qt host means every handler has to be
//! thread-safe and re-entrant, and a slow one stalls the network. Instead
//! `drain_events` returns everything queued since the last call, on the
//! caller's own thread, from a timer or an idle handler. Back-pressure is
//! bounded rather than unbounded: `Event::dropped` says how much was missed.
//!
//! **Absent numbers are negative, never zero.** A host drawing a tempo has to
//! tell "not playing" from "0.00 BPM", and zero cannot. `cxx` has no `Option`
//! in a shared struct, so the convention is explicit and applied everywhere:
//! `-1.0` means "no value", not a value of minus one.
//!
//! # Example
//!
//! ```cpp
//! #include "prolink-cxx/src/lib.rs.h"
//!
//! auto session = prolink::open(prolink::default_config());
//!
//! // From a UI timer, on your own thread:
//! for (const prolink::Event& event : session->drain_events()) {
//!     if (event.kind == prolink::EventKind::Beat) { /* ... */ }
//! }
//!
//! for (const prolink::Player& player : session->players()) {
//!     if (player.is_master) {
//!         meter->setPhase(player.bar_phase);
//!     }
//! }
//! ```

mod convert;
mod session;

pub use session::Session;

/// The shared vocabulary, and the entry points.
///
/// `cxx` generates the C++ declarations for everything in here, so a field
/// added on one side cannot go missing on the other: it is a compile error in
/// both languages rather than a layout mismatch at run time.
#[allow(
    unsafe_code,
    reason = "the bridge macro expands to the extern declarations that make \
              the two languages agree on layout and lifetime, and those cannot \
              be written safely. Nothing hand-written in this crate is unsafe, \
              which is the whole reason for choosing cxx over a C ABI."
)]
#[cxx::bridge(namespace = "prolink")]
pub mod ffi {
    /// What a device says it is.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum DeviceKind {
        /// Anything we have no name for.
        Unknown,
        /// A player.
        Cdj,
        /// A mixer.
        Mixer,
        /// rekordbox on a computer, and also the CDJ-3000.
        Rekordbox,
    }

    /// Which slot media is in.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum Slot {
        /// Nothing.
        None,
        /// The CD drive.
        Cd,
        /// The SD card.
        Sd,
        /// The USB slot.
        Usb,
        /// Another player's media, over LINK.
        Rekordbox,
    }

    /// What a platter is doing.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum PlayState {
        /// Nothing loaded.
        NoTrack,
        /// Loading.
        Loading,
        /// Playing.
        Playing,
        /// Playing inside a loop.
        Looping,
        /// Paused.
        Paused,
        /// Stopped at the cue point.
        Cued,
        /// Playing from the cue point while the button is held.
        CuePlay,
        /// Searching.
        Searching,
        /// Spun down.
        SpunDown,
        /// The medium went away mid-play and the deck is looping its buffer.
        Emergency,
        /// A value this library has never seen on the wire.
        Other,
    }

    /// What happened.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum EventKind {
        /// A device appeared.
        DeviceFound,
        /// A device's details changed.
        DeviceChanged,
        /// A device stopped sending keep-alives.
        DeviceLost,
        /// A player started a beat. `beat_in_bar` says which.
        Beat,
        /// A player's status changed: what is loaded, or what it is doing.
        PlayerChanged,
        /// Tempo master moved. `device` is the new master, or zero for nobody.
        TempoMaster,
        /// A player stopped sending beats.
        Stopped,
        /// A transfer advanced. `transfer`, `done` and `total` are set.
        TransferProgress,
        /// A transfer finished. `ok` says whether it succeeded, and `detail`
        /// carries the reason when it did not.
        TransferDone,
    }

    /// How to start a session.
    #[derive(Debug, Clone)]
    struct Config {
        /// The interface to use, or empty to choose one.
        ///
        /// Choosing automatically prefers a link-local address, which is what
        /// a DJ network always is; on a machine with two candidates it is a
        /// coin toss, so a host with a settings screen should name one.
        interface: String,

        /// Whether to announce as a virtual CDJ.
        ///
        /// **Off means the loaded track, the play state and the tempo master
        /// are never populated**, because a player unicasts status to peers
        /// that have announced themselves and to nobody else (F21). Tempo and
        /// beat phase still arrive, since beats are broadcast.
        announce: bool,
    }

    /// A network interface that could carry Pro DJ Link traffic.
    #[derive(Debug, Clone)]
    struct NetworkInterface {
        /// The system's name for it.
        name: String,
        /// Its IPv4 address.
        address: String,
        /// Its broadcast address.
        broadcast: String,
        /// Whether the address is link-local, which a DJ network's always is.
        ///
        /// A host choosing automatically should prefer these: a CDJ
        /// self-assigns in `169.254.0.0/16` after DHCP fails (F8).
        is_link_local: bool,
    }

    /// A device on the network.
    #[derive(Debug, Clone)]
    struct Device {
        /// 1–6 for a player, higher for other things.
        number: u8,
        /// What kind of device it says it is.
        kind: DeviceKind,
        /// Whether it is a player, and so something that can be browsed.
        is_player: bool,
        /// Whether it is still sending keep-alives.
        online: bool,
        /// Its hardware address, as `00:11:22:33:44:55`.
        mac: String,
        /// Its name. `CDJ-2000nexus` and the like.
        name: String,
        /// Its IPv4 address.
        address: String,
        /// Milliseconds since its last keep-alive.
        last_seen_ms: u64,
    }

    /// What one player is doing, as a host would render it.
    ///
    /// The fields that need a status packet — the loaded track, the play
    /// state, the tempo master — are populated only when the session
    /// announced itself (F21). `has_status` says whether they mean anything,
    /// so a host never draws a confident zero it was never told.
    #[derive(Debug, Clone)]
    struct Player {
        /// The player's number.
        number: u8,
        /// Its name.
        name: String,

        /// Whether the status fields below mean anything.
        has_status: bool,
        /// Whether it is sending beats, and so playing a rekordbox track.
        is_beating: bool,

        /// The tempo actually playing: the track's BPM with pitch applied.
        /// Negative when unknown.
        effective_bpm: f64,
        /// The track's own BPM, before pitch. Negative when unknown.
        track_bpm: f64,
        /// The pitch fader as a percentage, zero at centre.
        ///
        /// **Not the fader position while `is_synced`**: a synced deck slews
        /// this to hold its effective tempo equal to the master's (F51).
        pitch_percent: f64,

        /// Position within the current beat, `0.0` on the beat. Negative when
        /// the player is not beating or the estimate has gone stale.
        beat_phase: f64,
        /// Position within the four-beat bar, `0.0` on the downbeat. Negative
        /// when unknown.
        bar_phase: f64,
        /// Which beat of the bar, 1–4. Zero when the player has no bar to be
        /// in, which is what an unanalysed track reports.
        beat_in_bar: u8,

        /// Whether this player holds tempo master.
        is_master: bool,
        /// Whether SYNC is lit.
        is_synced: bool,
        /// The device it is handing master to, or zero.
        ///
        /// Non-zero for only the one or two packets of a handoff, during which
        /// **both** decks report themselves master; a host that ignores this
        /// will see mastership flicker (F52).
        yielding_to: u8,

        /// What the platter is doing.
        play_state: PlayState,
        /// The loaded track's row id, or zero.
        track_id: u32,
        /// Which player the loaded track came from.
        track_source_player: u8,
        /// Which of that player's slots.
        track_source_slot: Slot,
    }

    /// One thing that happened.
    ///
    /// Flat rather than a variant per kind, because C++ has no cheap sum type
    /// and a host switches on `kind` and reads the two or three fields that
    /// kind gives meaning to.
    #[derive(Debug, Clone)]
    struct Event {
        /// What happened.
        kind: EventKind,
        /// Which device, or zero where the event is not about one.
        device: u8,
        /// Which beat of the bar, for `Beat`. Zero otherwise.
        beat_in_bar: u8,
        /// How many events were discarded before this one because the host
        /// stopped draining.
        ///
        /// Non-zero means state was missed, and the host should re-read
        /// `devices()` and `players()` rather than trust its running picture.
        dropped: u32,

        /// Which transfer, for the two transfer kinds. Zero otherwise.
        transfer: u32,
        /// Bytes transferred so far, contiguous from the start of the file —
        /// never a running total that could exceed what is safely assembled.
        done: u64,
        /// Bytes the file holds. Zero if not yet known.
        total: u64,
        /// For `TransferDone`, whether it succeeded.
        ok: bool,
        /// For a failed `TransferDone`, why. Empty otherwise.
        detail: String,
    }

    extern "Rust" {
        /// A running session: sockets, timers, and the state they maintain.
        type Session;

        /// The interfaces that could carry Pro DJ Link traffic.
        fn interfaces() -> Vec<NetworkInterface>;

        /// A config that chooses an interface and announces.
        fn default_config() -> Config;

        /// Start a session. Throws on failure, with the reason.
        fn open(config: &Config) -> Result<Box<Session>>;

        /// The number we announced as, or zero if we did not announce.
        fn device_number(self: &Session) -> u8;

        /// Everyone on the network, as of now.
        fn devices(self: &Session) -> Vec<Device>;

        /// What every player is doing, as of now.
        fn players(self: &Session) -> Vec<Player>;

        /// Everything that has happened since the last call.
        ///
        /// Empty is the normal case. Call it from a timer; nothing is ever
        /// pushed from a network thread.
        fn drain_events(self: &Session) -> Vec<Event>;

        /// Fetch one file from a player's medium into `local_path`.
        ///
        /// Returns a transfer id. Progress arrives as `TransferProgress`
        /// events carrying that id, and exactly one `TransferDone` ends it.
        ///
        /// `remote_path` is taken verbatim from `export.pdb`, which stores
        /// paths relative to the medium root with a leading slash.
        ///
        /// **Nothing partial is ever written.** The file is assembled and
        /// written once, because a truncated `export.pdb` parses far enough to
        /// look plausible and then yields a library missing its last few
        /// hundred tracks.
        fn fetch_file(
            self: &Session,
            device_number: u8,
            slot: Slot,
            remote_path: &str,
            local_path: &str,
        ) -> Result<u32>;

        /// Fetch a player's `export.pdb`, the database a browse is built from.
        ///
        /// The same contract as `fetch_file`; this is the path a host does not
        /// have to know.
        fn fetch_database(
            self: &Session,
            device_number: u8,
            slot: Slot,
            local_path: &str,
        ) -> Result<u32>;
    }
}

pub use ffi::{
    Config, Device, DeviceKind, Event, EventKind, NetworkInterface, PlayState, Player, Slot,
};
pub use session::{default_config, interfaces, open};
