// SPDX-License-Identifier: GPL-3.0-only

//! A C++ binding for [`prolink`], generated by [`cxx`].
//!
//! Built for Mixxx, whose Pro DJ Link support is being replaced by calls into
//! this library, and shaped by that: the C++ side is meant to be a thin shell
//! that renders, so **everything here hands over state that is ready to
//! display** rather than parts a caller has to reassemble. There is no packet,
//! no socket and no parsing in this API.
//!
//! # Why `cxx` and not a C ABI
//!
//! A hand-written C header has to be kept in step with the Rust by hand, and
//! the failure mode when it is not is a caller's stack corrupted at run time,
//! on a machine the author does not have. `cxx` generates both sides from this
//! one file, so the same mistake is a compile error in both languages — and
//! `String` and `Vec` cross as `rust::String` and `rust::Vec` rather than as
//! fixed-size buffers with a length convention.
//!
//! Nothing on the C++ side of this boundary is `unsafe`, and nothing it
//! receives needs freeing.
//!
//! # Two rules the surface follows
//!
//! **Events are drained, never pushed.** A callback would be invoked from a
//! tokio worker thread, which for a Qt host means every handler has to be
//! thread-safe and re-entrant, and a slow one stalls the network. Instead
//! `drain_events` returns everything queued since the last call, on the
//! caller's own thread, from a timer or an idle handler. Back-pressure is
//! bounded rather than unbounded: `Event::dropped` says how much was missed.
//!
//! **Absent numbers are negative, never zero.** A host drawing a tempo has to
//! tell "not playing" from "0.00 BPM", and zero cannot. `cxx` has no `Option`
//! in a shared struct, so the convention is explicit and applied everywhere:
//! `-1.0` means "no value", not a value of minus one.
//!
//! # Example
//!
//! ```cpp
//! #include "prolink-cxx/src/lib.rs.h"
//!
//! auto session = prolink::open(prolink::default_config());
//!
//! // From a UI timer, on your own thread:
//! for (const prolink::Event& event : session->drain_events()) {
//!     if (event.kind == prolink::EventKind::Beat) { /* ... */ }
//! }
//!
//! for (const prolink::Player& player : session->players()) {
//!     if (player.is_master) {
//!         meter->setPhase(player.bar_phase);
//!     }
//! }
//! ```

mod anlz;
mod browse;
mod convert;
mod logging;
mod pdb;
mod serve;
mod session;

pub use logging::init_logging;
pub use session::Session;

/// The shared vocabulary, and the entry points.
///
/// `cxx` generates the C++ declarations for everything in here, so a field
/// added on one side cannot go missing on the other: it is a compile error in
/// both languages rather than a layout mismatch at run time.
#[allow(
    unsafe_code,
    reason = "the bridge macro expands to the extern declarations that make \
              the two languages agree on layout and lifetime, and those cannot \
              be written safely. Nothing hand-written in this crate is unsafe, \
              which is the whole reason for choosing cxx over a C ABI."
)]
#[cxx::bridge(namespace = "prolink")]
pub mod ffi {
    /// What a device says it is.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum DeviceKind {
        /// Anything we have no name for.
        Unknown,
        /// A player.
        Cdj,
        /// A mixer.
        Mixer,
        /// rekordbox on a computer, and also the CDJ-3000.
        Rekordbox,
    }

    /// Which slot media is in.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum Slot {
        /// Nothing.
        None,
        /// The CD drive.
        Cd,
        /// The SD card.
        Sd,
        /// The USB slot.
        Usb,
        /// Another player's media, over LINK.
        Rekordbox,
    }

    /// What a platter is doing.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum PlayState {
        /// Nothing loaded.
        NoTrack,
        /// Loading.
        Loading,
        /// Playing.
        Playing,
        /// Playing inside a loop.
        Looping,
        /// Paused.
        Paused,
        /// Stopped at the cue point.
        Cued,
        /// Playing from the cue point while the button is held.
        CuePlay,
        /// Searching.
        Searching,
        /// Spun down.
        SpunDown,
        /// The medium went away mid-play and the deck is looping its buffer.
        Emergency,
        /// A value this library has never seen on the wire.
        Other,
    }

    /// What happened.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    enum EventKind {
        /// A device appeared.
        DeviceFound,
        /// A device's details changed.
        DeviceChanged,
        /// A device stopped sending keep-alives.
        DeviceLost,
        /// A player started a beat. `beat_in_bar` says which.
        Beat,
        /// A player's status changed: what is loaded, or what it is doing.
        PlayerChanged,
        /// Tempo master moved. `device` is the new master, or zero for nobody.
        TempoMaster,
        /// A player stopped sending beats.
        Stopped,
        /// A transfer advanced. `transfer`, `done` and `total` are set.
        TransferProgress,
        /// A transfer finished. `ok` says whether it succeeded, `detail`
        /// carries the reason when it did not, and `path` is where it was
        /// written.
        TransferDone,
        /// A player described one of its slots: volume name and counts.
        ///
        /// A deck sends this once, when it first browses a slot, so a host
        /// that only polls `media()` may wait a long time for it (F37).
        MediaInfo,
    }

    /// How to start a session.
    #[derive(Debug, Clone)]
    struct Config {
        /// The interface to use, or empty to choose one.
        ///
        /// Choosing automatically prefers a link-local address, which is what
        /// a DJ network always is; on a machine with two candidates it is a
        /// coin toss, so a host with a settings screen should name one.
        interface: String,

        /// Whether to announce as a virtual CDJ.
        ///
        /// **Off means the loaded track, the play state and the tempo master
        /// are never populated**, because a player unicasts status to peers
        /// that have announced themselves and to nobody else (F21). Tempo and
        /// beat phase still arrive, since beats are broadcast.
        announce: bool,

        /// The player number to ask for, 1–4, or 0 for whichever is free.
        ///
        /// Not a cosmetic choice, and not a number to invent: a deck offers
        /// LINK sources and answers browse requests only for players 1–4, and
        /// at any other number it accepts the announcement in full and then
        /// silently never asks us anything (F45). The claim chain negotiates
        /// for real — it watches first, backs off when a number is defended,
        /// and defends the one it takes — so this is a preference, not an
        /// assertion.
        ///
        /// A host restarting a session should pass back the number it last
        /// held, so a refresh keeps the identity the decks already know.
        preferred_number: u8,

        /// Whether to offer this machine's own rekordbox sticks to the players.
        ///
        /// On, the session scans the mount points every two seconds and serves
        /// what it finds — USB first, then SD, which is all a CDJ has. That is
        /// what makes this machine appear in a deck's LINK menu; a player with
        /// no media is listed nowhere, whatever its number (F24).
        ///
        /// Off, `serve_media` still works: a host that knows its own media,
        /// or wants a stick the DJ chose rather than every stick, drives it
        /// directly.
        share_local_media: bool,
    }

    /// A network interface that could carry Pro DJ Link traffic.
    #[derive(Debug, Clone)]
    struct NetworkInterface {
        /// The system's name for it.
        name: String,
        /// Its IPv4 address.
        address: String,
        /// Its broadcast address.
        broadcast: String,
        /// Whether the address is link-local, which a DJ network's always is.
        ///
        /// A host choosing automatically should prefer these: a CDJ
        /// self-assigns in `169.254.0.0/16` after DHCP fails (F8).
        is_link_local: bool,
    }

    /// A device on the network.
    #[derive(Debug, Clone)]
    struct Device {
        /// 1–6 for a player, higher for other things.
        number: u8,
        /// What kind of device it says it is.
        kind: DeviceKind,
        /// Whether it is a player, and so something that can be browsed.
        is_player: bool,
        /// Whether it is still sending keep-alives.
        online: bool,
        /// Its hardware address, as `00:11:22:33:44:55`.
        mac: String,
        /// Its name. `CDJ-2000nexus` and the like.
        name: String,
        /// Its IPv4 address.
        address: String,
        /// Milliseconds since its last keep-alive.
        last_seen_ms: u64,
    }

    /// What one player is doing, as a host would render it.
    ///
    /// The fields that need a status packet — the loaded track, the play
    /// state, the tempo master — are populated only when the session
    /// announced itself (F21). `has_status` says whether they mean anything,
    /// so a host never draws a confident zero it was never told.
    #[derive(Debug, Clone)]
    struct Player {
        /// The player's number.
        number: u8,
        /// Its name.
        name: String,

        /// Whether the status fields below mean anything.
        has_status: bool,
        /// Whether it is sending beats, and so playing a rekordbox track.
        is_beating: bool,

        /// The tempo actually playing: the track's BPM with pitch applied.
        /// Negative when unknown.
        effective_bpm: f64,
        /// The track's own BPM, before pitch. Negative when unknown.
        track_bpm: f64,
        /// The pitch fader as a percentage, zero at centre.
        ///
        /// **Not the fader position while `is_synced`**: a synced deck slews
        /// this to hold its effective tempo equal to the master's (F51).
        pitch_percent: f64,

        /// Position within the current beat, `0.0` on the beat. Negative when
        /// the player is not beating or the estimate has gone stale.
        beat_phase: f64,
        /// Position within the four-beat bar, `0.0` on the downbeat. Negative
        /// when unknown.
        bar_phase: f64,
        /// Which beat of the bar, 1–4. Zero when the player has no bar to be
        /// in, which is what an unanalysed track reports.
        beat_in_bar: u8,

        /// Whether this player holds tempo master.
        is_master: bool,
        /// Whether SYNC is lit.
        is_synced: bool,
        /// The device it is handing master to, or zero.
        ///
        /// Non-zero for only the one or two packets of a handoff, during which
        /// **both** decks report themselves master; a host that ignores this
        /// will see mastership flicker (F52).
        yielding_to: u8,

        /// What the platter is doing.
        play_state: PlayState,
        /// The loaded track's row id, or zero.
        track_id: u32,
        /// Which player the loaded track came from.
        track_source_player: u8,
        /// Which of that player's slots.
        track_source_slot: Slot,
    }

    /// A row in a browse menu: a track, an artist, an album, a category.
    #[derive(Debug, Clone)]
    struct Row {
        /// What the row names — a track id in a track list, an artist id in an
        /// artist list. What to pass back when the user opens it.
        id: u32,
        /// The first line: a title, a name, a category label.
        label: String,
        /// The second line, which the sort chooses: the artist under a title,
        /// the tempo under a BPM sort. Empty when the sort is numeric.
        detail: String,
        /// The raw item type, so a host can tell a track row from a category
        /// row without matching on the label.
        item_type: u32,
        /// The artwork to fetch for this row, or zero.
        artwork_id: u32,
        /// Its 1-based position inside a playlist, or its track number.
        position: u32,
        /// Whether this row is the track the browsing deck has loaded.
        is_loaded: bool,
        /// Whether this row is in the deck's tag list.
        is_tagged: bool,
    }

    /// Everything a deck will tell us about one track.
    #[derive(Debug, Clone)]
    struct Metadata {
        /// The track's row id.
        id: u32,
        /// Its title.
        title: String,
        /// Its artist.
        artist: String,
        /// Its album.
        album: String,
        /// Its genre.
        genre: String,
        /// Its musical key, as the medium spells it — Camelot on one export,
        /// classical on another, because that is a rekordbox setting.
        key: String,
        /// Its record label.
        label: String,
        /// Its colour tag.
        colour: String,
        /// The DJ comment.
        comment: String,
        /// When it was added, as `2025-06-24`.
        date_added: String,
        /// How long it runs, in seconds.
        duration_seconds: u32,
        /// Its tempo in hundredths of a BPM, before any pitch fader.
        tempo_centibpm: u32,
        /// Its star rating.
        rating: u32,
        /// Its bitrate in kbps.
        bitrate: u32,
        /// The artwork to fetch, or zero.
        artwork_id: u32,
    }

    /// What one of a player's slots holds.
    #[derive(Debug, Clone)]
    struct MediaInfo {
        /// Which player.
        device: u8,
        /// Which slot.
        slot: Slot,
        /// Whether a medium is present and mounted.
        has_media: bool,
        /// The volume name, empty until the player has described the slot.
        volume_name: String,
        /// When the export was written, as `2025-06-24`. Empty until known.
        created: String,
        /// How many tracks it holds. Zero until known.
        track_count: u32,
        /// How many playlists. Zero until known.
        playlist_count: u32,
    }

    /// How to serve local media to real players.
    #[derive(Debug, Clone)]
    struct ServeConfig {
        /// The interface to use, or empty to choose one.
        interface: String,
        /// The medium to present in the USB slot, or empty for none.
        usb_path: String,
        /// The medium to present in the SD slot, or empty for none.
        ///
        /// A second USB stick shown as an SD card is exactly what a CDJ
        /// expects to see.
        sd_path: String,
    }

    /// One of our own slots, as we offer it.
    #[derive(Debug, Clone)]
    struct ServedSlot {
        /// Which slot we present it in.
        slot: Slot,
        /// The volume name a deck shows.
        volume_name: String,
        /// Where it came from on this machine.
        local_path: String,
        /// The NFS export path a deck mounts.
        export_path: String,
        /// How many tracks it holds.
        track_count: u32,
        /// How many playlists.
        playlist_count: u32,
        /// Whether the medium behind this is **gone** while a player is still
        /// playing off it.
        ///
        /// It stays announced, because that is what keeps the consumer's mount
        /// valid and its player from erroring out mid-track, and it is served
        /// from copies made while the stick was in. It is no longer browsable:
        /// menus answer empty, so nobody can start something we could not
        /// finish. It leaves for real once the last consumer moves on.
        phantom: bool,
    }

    /// A player that has taken a track off our media.
    #[derive(Debug, Clone)]
    struct ServeConsumer {
        /// Which player.
        device_number: u8,
        /// Its name.
        device_name: String,
        /// Its address.
        address: String,
        /// Which of our slots it took the track from.
        slot: Slot,
        /// The track's row id.
        track_id: u32,
        /// Whether it is playing right now.
        playing: bool,
    }

    /// What a running server is doing.
    #[derive(Debug, Clone)]
    struct ServeStatus {
        /// Whether we hold a player number, without which nothing else here
        /// matters: a deck validates it in every dbserver request (F45).
        active: bool,
        /// The number we hold, 1–4.
        device_number: u8,
        /// The address we serve from.
        address: String,
        /// The interface we serve on.
        interface: String,
        /// Where the portmapper is listening.
        ///
        /// **Must be 111.** With nothing there a deck retries `GETPORT` once a
        /// second for ever rather than falling back to the well-known ports,
        /// and never reaches the dbserver at all (F46).
        portmap_port: u16,
        /// Where mountd is listening.
        mount_port: u16,
        /// Where nfsd is listening.
        nfs_port: u16,
        /// Where the dbserver is listening.
        dbserver_port: u16,
        /// Whether a real player can actually find us — the portmapper is on
        /// 111 and we hold a browsable number.
        is_discoverable: bool,
        /// The media we are offering.
        media: Vec<ServedSlot>,
        /// The players reading from us, and what each has loaded.
        consumers: Vec<ServeConsumer>,
    }

    /// One track, as `export.pdb` stores it.
    ///
    /// The names are resolved as well as their row ids given: a host that only
    /// wants to show a track never has to join anything, and one building a
    /// browse tree still can.
    #[derive(Debug, Clone)]
    struct PdbTrack {
        /// The row id, which is what every other request names a track by.
        id: u32,
        /// The track's title.
        title: String,
        /// Its artist, resolved from the artist table.
        artist: String,
        /// Its album.
        album: String,
        /// Its genre.
        genre: String,
        /// Its musical key, as the medium spells it.
        key: String,
        /// Its record label.
        label: String,
        /// Its colour tag.
        color: String,
        /// The DJ comment.
        comment: String,
        /// The path on the medium, with a leading slash, exactly as the
        /// database stores it — which is what a fetch takes verbatim.
        file_path: String,
        /// The `.DAT` beside it, holding the beat grid and waveforms.
        analyze_path: String,
        /// The artwork file on the medium, if it has one.
        artwork_path: String,
        /// When it was added, as `2025-06-24`.
        date_added: String,
        /// Its release year, or zero.
        year: u32,
        /// How long it runs.
        duration_seconds: u32,
        /// In kbps.
        bitrate: u32,
        /// Hundredths of a BPM, so 145.00 is 14500.
        tempo_centibpm: u32,
        /// Its star rating.
        rating: u32,
        /// The artwork to fetch, or zero.
        artwork_id: u32,
        /// In Hz.
        sample_rate: u32,
        /// In bytes.
        file_size: u32,
        /// Its number within its album.
        track_number: u32,
        /// Its disc, for a multi-disc album.
        disc_number: u32,
        /// How many times a deck has played it.
        play_count: u32,
        /// The container byte, which is what a deck uses to decide how to
        /// decode the file.
        file_type: u32,
        /// The artist's row id, for a browse tree.
        artist_id: u32,
        /// The album's row id.
        album_id: u32,
        /// The genre's row id.
        genre_id: u32,
        /// The key's row id. Per-medium, not a canonical index.
        key_id: u32,
        /// The label's row id.
        label_id: u32,
        /// The colour's palette index.
        color_id: u32,
    }

    /// A playlist, or a folder of them.
    #[derive(Debug, Clone)]
    struct PdbPlaylist {
        /// Its row id.
        id: u32,
        /// The folder it sits in, or zero at the top level.
        parent_id: u32,
        /// Where it sorts among its siblings.
        sort_order: u32,
        /// Its name.
        name: String,
        /// Whether it holds other playlists rather than tracks.
        is_folder: bool,
        /// Empty for a folder, and in the DJ's own order for a playlist.
        track_ids: Vec<u32>,
    }

    /// One history playlist: what a player played off this medium, in order.
    ///
    /// rekordbox writes one of these every time a player mounts the medium, so
    /// a well-travelled stick carries a session per gig. They are the only
    /// record of what was played that survives on the medium itself -- a deck
    /// that mounts read-only, as TriMixxx does, never adds to them.
    ///
    /// There is no timestamp anywhere in the format. Order is all there is:
    /// later row id means a later session, and later position within one means
    /// later in that session.
    #[derive(Debug, Clone)]
    struct PdbHistoryPlaylist {
        /// Its row id. Ascending with the session, which is what makes it
        /// usable as a clock.
        id: u32,
        /// `HISTORY 001` and so on.
        name: String,
        /// The tracks, in the order they were played.
        track_ids: Vec<u32>,
    }

    /// One beat of a `PQTZ` grid.
    ///
    /// `time_ms` is the beat's position and `tempo` is what rekordbox analysed
    /// it at. Both are given because they disagree, and which one a host should
    /// believe depends on the track: rekordbox writes beat times as **whole
    /// milliseconds**, so at 144 BPM the stored gaps alternate 417, 417, 416 and
    /// a grid built from them has a tempo that swings by up to 0.45 BPM
    /// depending on which pair of beats is measured. `tempo` is centi-BPM and
    /// exact. A host that finds one distinct tempo across the grid should use
    /// it and anchor at the first beat; one that finds several has a genuinely
    /// variable-tempo track and nothing but the positions.
    #[derive(Debug, Clone)]
    struct AnlzBeat {
        /// Which beat of the bar, 1-4. The first beat numbered 1 is the only
        /// record of the grid's phase.
        beat_number: u16,
        /// Centi-BPM at this beat.
        tempo: u16,
        /// Milliseconds from the start of the track.
        time_ms: u32,
    }

    /// One cue or loop, from either cue tag.
    ///
    /// Flat rather than two types, because a host applies both in one pass and
    /// the older tag is simply the newer one without the comment and the
    /// colours. `extended` says which tag it came from, so a host can tell an
    /// absent comment from an empty one.
    #[derive(Debug, Clone)]
    struct AnlzCue {
        /// True when this came from `PCO2`, and so when the comment and colour
        /// fields below mean anything.
        extended: bool,
        /// True for the hot-cue list, false for the memory-cue list. **A file
        /// carries one list of each**, so a reader that takes the first tag
        /// gets half the cues and no error.
        hot_list: bool,
        /// 0 for a memory cue, 1 for hot cue A, 2 for B, and so on.
        hot_cue: u32,
        /// True when this is a loop and `loop_time_ms` means something.
        is_loop: bool,
        /// Where it sits, in milliseconds at normal pitch.
        time_ms: u32,
        /// Where a loop jumps back from, in milliseconds. Zero unless `is_loop`.
        loop_time_ms: u32,
        /// The DJ's comment, already out of the file's UTF-16BE. Empty unless
        /// `extended`.
        comment: String,
        /// Row id in rekordbox's colour table, for a memory cue given one.
        color_id: u32,
        /// Red component of the colour a player lights the pad with. Zero
        /// unless `extended`.
        color_red: u8,
        /// Green component.
        color_green: u8,
        /// Blue component.
        color_blue: u8,
    }

    /// One column of the `PWV5` colour scrolling waveform.
    ///
    /// **The three bands are a hue and `height` is the amplitude**, which is
    /// what makes this a colour waveform rather than three waveforms. The bands
    /// sit near saturation whatever the track is doing and correlate with the
    /// height at only 0.0-0.4, while the height correlates with the monochrome
    /// `PWV3` waveform of the same track at 0.99. A renderer that derives its
    /// height from the bands draws the spectral balance instead of the
    /// envelope, quantised to the eight levels three bits allow.
    #[derive(Debug, Clone)]
    struct AnlzColourColumn {
        /// Bits 15-13. The loudest and slowest-varying band, drawn red.
        bass: u8,
        /// Bits 9-7. Drawn green.
        mid: u8,
        /// Bits 12-10. The quietest and spikiest band, drawn blue.
        treble: u8,
        /// Bits 6-2. The envelope, 0-31.
        height: u8,
    }

    /// Everything read out of one `ANLZ####.DAT` or `.EXT`.
    ///
    /// Whichever of these a file has: a `.DAT` carries the grid and the plain
    /// cues, a `.EXT` the extended cues and the colour waveforms. An absent tag
    /// is an empty vector and not an error — which tags a file has depends on
    /// the rekordbox version that wrote it.
    #[derive(Debug, Clone)]
    struct AnlzContents {
        /// Whether the file parsed. On false the rest is empty and `error` says
        /// why. A tag that does not parse costs that tag, not the file, and
        /// leaves `ok` true.
        ok: bool,
        /// Why it did not parse. Empty when `ok`.
        error: String,
        /// `PQTZ`, the beat grid.
        beats: Vec<AnlzBeat>,
        /// `PCOB` and `PCO2`, both lists of each, in file order.
        cues: Vec<AnlzCue>,
        /// `PWV5`, the colour scrolling waveform, at 150 columns per second.
        colour_detail: Vec<AnlzColourColumn>,
        /// `PWAV`, the preview waveform: 400 packed bytes, height in the low
        /// five bits and shade in the top three.
        preview: Vec<u8>,
    }

    /// A row of one of the lookup tables, for building a browse tree.
    #[derive(Debug, Clone)]
    struct PdbNamed {
        /// The row id a track refers to.
        id: u32,
        /// What to show for it.
        name: String,
    }

    /// Everything read out of one `export.pdb`.
    #[derive(Debug, Clone)]
    struct PdbContents {
        /// Whether it parsed. On false the rest is empty and `error` says why.
        ok: bool,
        /// Why it did not parse. Empty when `ok`.
        error: String,
        /// Every track on the medium.
        tracks: Vec<PdbTrack>,
        /// Every playlist and folder.
        playlists: Vec<PdbPlaylist>,
        /// One per player mount: what was played off this medium, in order.
        history: Vec<PdbHistoryPlaylist>,
        /// The artist table.
        artists: Vec<PdbNamed>,
        /// The album table.
        albums: Vec<PdbNamed>,
        /// The genre table.
        genres: Vec<PdbNamed>,
        /// The key table. Its ids are per-medium.
        keys: Vec<PdbNamed>,
        /// The record-label table.
        labels: Vec<PdbNamed>,
        /// The colour palette.
        colors: Vec<PdbNamed>,
        /// The artwork table: id to file path.
        artwork: Vec<PdbNamed>,
    }

    /// One thing that happened.
    ///
    /// Flat rather than a variant per kind, because C++ has no cheap sum type
    /// and a host switches on `kind` and reads the two or three fields that
    /// kind gives meaning to.
    #[derive(Debug, Clone)]
    struct Event {
        /// What happened.
        kind: EventKind,
        /// Which device, or zero where the event is not about one.
        device: u8,
        /// Which beat of the bar, for `Beat`. Zero otherwise.
        beat_in_bar: u8,
        /// How many events were discarded before this one because the host
        /// stopped draining.
        ///
        /// Non-zero means state was missed, and the host should re-read
        /// `devices()` and `players()` rather than trust its running picture.
        dropped: u32,

        /// Which transfer, for the two transfer kinds. Zero otherwise.
        transfer: u32,
        /// Bytes transferred so far, in total. A fraction to show a user, and
        /// **not** a statement about which bytes are on disk: a streaming fetch
        /// takes the head, then the tail, then the middle, so after two steps
        /// `done` counts bytes that are not contiguous with each other.
        ///
        /// Anything deciding whether a byte may be read must use `offset` and
        /// `len` instead. Reading a hole is silent — it yields the zeros of a
        /// sparse file rather than an error — so the difference matters far more
        /// than it looks.
        done: u64,
        /// Bytes the file holds. Zero if not yet known.
        ///
        /// A streaming fetch announces the size on its own, in a first event
        /// with `len` zero, as soon as the file has been opened and stat'd.
        /// That is what lets a host size its view of the file and start
        /// decoding without waiting for any content at all.
        total: u64,
        /// For `TransferProgress`, where the range that just landed starts.
        offset: u64,
        /// For `TransferProgress`, how long that range is. Zero when the event
        /// carries no new bytes — the size announcement above, and the final
        /// summary — and such an event must not be taken as data arriving.
        len: u64,
        /// For `TransferDone`, whether it succeeded.
        ok: bool,
        /// For a failed `TransferDone`, why. Empty otherwise.
        detail: String,
        /// For `TransferDone`, the local path it was written to.
        ///
        /// Carried as well as the id, because a host that keyed its own state
        /// on the path it asked for should not have to keep an id table to get
        /// back to it.
        path: String,
        /// For `MediaInfo`, which slot was described.
        slot: Slot,
    }

    extern "Rust" {
        /// A running session: sockets, timers, and the state they maintain.
        type Session;

        /// The interfaces that could carry Pro DJ Link traffic.
        fn interfaces() -> Vec<NetworkInterface>;

        /// A config that chooses an interface and announces.
        fn default_config() -> Config;

        /// Send this library's own log to standard error.
        ///
        /// Off until asked for, because a host owns its output and a library
        /// that writes to it uninvited is a nuisance. But the protocol's
        /// diagnosis lives in these lines and nowhere else — which player
        /// number was claimed and why, which stick was mounted, and whether
        /// the portmapper got port 111, without which no deck will ever list
        /// us however well everything else works (F46).
        ///
        /// `filter` is a `tracing` directive: empty for a sensible default of
        /// `prolink=info`, `prolink=debug` for the packet-level detail, or
        /// whatever `PROLINK_LOG` says when that is set — which wins, so a
        /// deck can be turned up without a rebuild.
        ///
        /// Safe to call more than once; only the first call installs anything.
        fn init_logging(filter: &str);

        /// Read a rekordbox `export.pdb` off disk.
        ///
        /// Never throws: a database that does not parse comes back with `ok`
        /// false and `error` set, because a host that has just pulled several
        /// megabytes over NFS wants to show the user why rather than unwind.
        fn read_pdb(path: &str) -> PdbContents;

        /// Read a rekordbox `export.pdb` a host already has in memory.
        ///
        /// The same contract as `read_pdb`. This is the one a host that
        /// fetched the database itself wants, so that reading the file and
        /// parsing it stay separate failures with separate messages.
        fn read_pdb_bytes(bytes: &[u8]) -> PdbContents;

        /// Read one `ANLZ####.DAT` or `.EXT` off disk.
        ///
        /// Never throws, like `read_pdb`: a file that does not parse comes
        /// back with `ok` false and `error` set. A missing file is the same
        /// answer — analysis is an enhancement, and a track with no grid
        /// still plays.
        ///
        /// A free function and not a `Session` method, so it is safe to call
        /// from a worker thread with no session running at all.
        fn read_anlz(path: &str) -> AnlzContents;

        /// Start a session. Throws on failure, with the reason.
        fn open(config: &Config) -> Result<Box<Session>>;

        /// The number we announced as, or zero if we did not announce.
        fn device_number(self: &Session) -> u8;

        /// Everyone on the network, as of now.
        fn devices(self: &Session) -> Vec<Device>;

        /// What every player is doing, as of now.
        fn players(self: &Session) -> Vec<Player>;

        /// Tell the network what this host is playing.
        ///
        /// **Without this we are a device with no tempo.** Everything else
        /// here reads the network; this is the one call that makes us
        /// something other players can beat-match to, and until it is made no
        /// CDJ will draw a phase for us however well the rest works.
        ///
        /// `bpm` is the track's own tempo before the fader and
        /// `pitch_percent` the fader itself, as the wire carries them.
        /// `beat_number` counts beats from 1, and `beat_fraction` is how far
        /// through that beat the playhead is. Zero for `beat_number` means
        /// there is no grid to publish.
        ///
        /// Call it from a timer several times a second. Beats between calls
        /// are projected from the tempo, so this rate sets how fast a tempo
        /// change propagates, not the accuracy of the beats.
        fn set_playback(
            self: &Session,
            bpm: f64,
            pitch_percent: f64,
            playing: bool,
            beat_number: u32,
            beat_fraction: f64,
        );

        /// State what this host has loaded, and whose medium it came from.
        ///
        /// **A tempo without this is ignored.** A deck publishes both or
        /// neither; a CDJ asked to follow a master that claims a tempo and no
        /// track does not follow it. `source_player` is the player whose
        /// medium the track came from — our own number when playing off our
        /// own stick — and `track_id` is the rekordbox row id.
        fn set_loaded_track(self: &Session, source_player: u8, slot: Slot, track_id: u32);

        /// Nothing is loaded here. The network stops seeing a tempo from us.
        fn clear_playback(self: &Session);

        /// Take tempo master, asking whoever holds it to hand over first.
        ///
        /// Returns immediately. If another device holds master the claim only
        /// takes effect once that device has yielded, which takes a packet or
        /// two — watch `is_tempo_master`.
        fn take_tempo_master(self: &Session);

        /// Whether SYNC is engaged here.
        ///
        /// Published as flag bit 4, which is what a CDJ lights its own SYNC
        /// button from and what says this deck is following rather than flying
        /// its own tempo.
        fn set_synced(self: &Session, synced: bool);

        /// Give up tempo master.
        fn release_tempo_master(self: &Session);

        /// Whether we are claiming tempo master.
        fn is_tempo_master(self: &Session) -> bool;

        /// Everything that has happened since the last call.
        ///
        /// Empty is the normal case. Call it from a timer; nothing is ever
        /// pushed from a network thread.
        fn drain_events(self: &Session) -> Vec<Event>;

        /// Fetch one file from a player's medium into `local_path`.
        ///
        /// Returns a transfer id. Progress arrives as `TransferProgress`
        /// events carrying that id, and exactly one `TransferDone` ends it.
        ///
        /// `remote_path` is taken verbatim from `export.pdb`, which stores
        /// paths relative to the medium root with a leading slash.
        ///
        /// **Nothing partial is ever written.** The file is assembled and
        /// written once, because a truncated `export.pdb` parses far enough to
        /// look plausible and then yields a library missing its last few
        /// hundred tracks.
        /// Fetch a track head-first so it can be played before it has fully
        /// arrived.
        ///
        /// The local file is created at its full size immediately, sparse, so a
        /// decoder reading it sees the right duration from the start. Then:
        ///
        ///  * the **first** `TransferProgress` carries `total` and nothing else
        ///    — the size, as soon as the file has been opened and stat'd, which
        ///    is everything a caller needs to start;
        ///  * each one after it carries the `offset` and `len` of a range that
        ///    has landed and been flushed, head first, then tail, then the
        ///    middle in playhead order;
        ///  * `TransferDone` means the whole file is local.
        ///
        /// **The gaps are real.** Until a range has been announced, that part
        /// of the file is a sparse hole and reads back as zeros, successfully.
        /// A caller that decodes ahead of the announcements gets silence, not
        /// an error, so it must block on anything it has not been told about.
        fn fetch_file_streaming(
            self: &Session,
            device_number: u8,
            slot: Slot,
            remote_path: &str,
            local_path: &str,
            head_bytes: u32,
        ) -> Result<u32>;

        fn fetch_file(
            self: &Session,
            device_number: u8,
            slot: Slot,
            remote_path: &str,
            local_path: &str,
        ) -> Result<u32>;

        /// Whether the sockets are up and we are hearing the network.
        fn is_listening(self: &Session) -> bool;

        /// Offer a local rekordbox medium to the players on the network.
        ///
        /// `path` is the mount point — the directory holding `PIONEER/`.
        /// Replaces whatever was in that slot. Returns at once; reading the
        /// database and walking the files takes a second or two, and a path
        /// that is not a rekordbox export is reported through `last_error`.
        ///
        /// Not needed when `Config::share_local_media` is on, which serves
        /// every stick this machine has.
        fn serve_media(self: &Session, slot: Slot, path: &str);

        /// Stop offering whatever is in a slot.
        ///
        /// Ejects it first, which takes a couple of seconds when a deck is
        /// reading from us — it is told through the slot state in our status
        /// packets and answers with UMNT. Returns at once; the eject happens
        /// on the session's own runtime.
        fn stop_serving(self: &Session, slot: Slot);

        /// What we are offering, and which players are reading it.
        fn serve_status(self: &Session) -> ServeStatus;

        /// The interface currently bound, or empty if none is.
        ///
        /// Not fixed for the life of the session: a host is often started
        /// before its ethernet is plugged in, and the session moves when a
        /// better interface appears.
        fn interface_name(self: &Session) -> String;

        /// Whether startup has finished.
        ///
        /// `open` returns before the sockets are bound, because claiming a
        /// player number takes about five seconds of watching and negotiating
        /// and a host must not spend that frozen. Until this is true
        /// `device_number` is zero and the tables are empty; if it stays false,
        /// `last_error` says what went wrong.
        fn is_ready(self: &Session) -> bool;

        /// The last thing that went wrong, or empty. For a status line.
        fn last_error(self: &Session) -> String;

        /// Forget every device and re-learn the network.
        ///
        /// A host offers this when a user has re-cabled the rig: a deck that
        /// vanished without a keep-alive is otherwise held for the full
        /// timeout.
        fn refresh(self: &mut Session);

        /// What every player's slots hold, as of now.
        ///
        /// A slot a player has not yet described comes back with
        /// `has_media` true and the counts zero: the presence is published in
        /// every status packet, the description only when a deck first asks
        /// (F20, F37).
        fn media(self: &Session) -> Vec<MediaInfo>;

        /// The root menu of a player's slot, as its LINK button shows it.
        ///
        /// **Blocks on the network, and claims a browsable device number the
        /// first time.** Call it off the UI thread; a dbserver request needs a
        /// number in 1–4, which contends with the decks for one (F45).
        fn root_menu(self: &mut Session, device_number: u8, slot: Slot) -> Result<Vec<Row>>;

        /// Every track on a player's slot, under the given sort.
        ///
        /// Blocks; see `root_menu`. `sort` is zero for the default, which is
        /// by title.
        fn track_rows(
            self: &mut Session,
            device_number: u8,
            slot: Slot,
            sort: u32,
        ) -> Result<Vec<Row>>;

        /// Search a player's slot, the way its on-screen keyboard does.
        ///
        /// Blocks; see `root_menu`. The term is upper-cased on the way out,
        /// because a deck's own keyboard has no lower case and its dbserver is
        /// case-sensitive (F44).
        fn search(
            self: &mut Session,
            device_number: u8,
            slot: Slot,
            term: &str,
        ) -> Result<Vec<Row>>;

        /// Everything a player will say about one track.
        ///
        /// Blocks; see `root_menu`.
        fn metadata(
            self: &mut Session,
            device_number: u8,
            slot: Slot,
            track_id: u32,
        ) -> Result<Metadata>;

        /// Fetch a track's artwork into `local_path`.
        ///
        /// Returns a transfer id and does **not** block: the answer arrives as
        /// a `TransferDone` event carrying that id and the path.
        ///
        /// A host asks for these by the hundred — a 651-track medium has some
        /// six hundred distinct covers — so a blocking call would freeze a UI
        /// for six hundred round trips. They are queued onto one connection
        /// and answered in order.
        ///
        /// **Over dbserver, not NFS.** Two full load-and-play captures contain
        /// LOOKUPs for audio files and not one image; asking NFS for covers
        /// works for the first hundred and then fails wholesale, because
        /// walking `PIONEER/Artwork/000NN` per image churns the player's
        /// filehandle table until it answers `NFSERR_STALE` to handles a
        /// millisecond old (F28).
        fn fetch_artwork(
            self: &Session,
            device_number: u8,
            slot: Slot,
            artwork_id: u32,
            local_path: &str,
        ) -> Result<u32>;

        /// The device number a MAC currently holds, or zero.
        ///
        /// A player's *number* can be reassigned while its MAC cannot, so a
        /// host that keeps a request across time should hold the MAC and
        /// resolve it here rather than cache the number.
        fn device_number_of(self: &Session, mac: &str) -> u8;

        /// Fetch a player's `export.pdb`, the database a browse is built from.
        ///
        /// The same contract as `fetch_file`; this is the path a host does not
        /// have to know.
        fn fetch_database(
            self: &Session,
            device_number: u8,
            slot: Slot,
            local_path: &str,
        ) -> Result<u32>;
    }

    extern "Rust" {
        /// A running server: our media, offered to real players.
        type Server;

        /// Start serving. Throws on failure, with the reason.
        ///
        /// **Needs UDP/111**, which is privileged: run as root, or on Linux
        /// set `net.ipv4.ip_unprivileged_port_start=111`. Without it a deck
        /// retries `GETPORT` once a second for ever and never finds us (F46).
        fn serve(config: &ServeConfig) -> Result<Box<Server>>;

        /// What this server is doing.
        fn status(self: &Server) -> ServeStatus;

        /// Stop serving, ejecting the media first.
        ///
        /// Not the same as dropping it. A deck reading our files has a mount
        /// open, and sockets that simply vanish leave it retrying against
        /// nothing; ejecting walks each slot through the unmounting states a
        /// consumer waits for before the slot goes empty (F20).
        fn stop(self: &mut Server);
    }
}

pub use ffi::{
    Config, Device, DeviceKind, Event, EventKind, MediaInfo, Metadata, NetworkInterface,
    PdbContents, PdbNamed, PdbPlaylist, PdbTrack, PlayState, Player, Row, ServeConfig,
    ServeConsumer, ServeStatus, ServedSlot, Slot,
};
pub use serve::{Server, serve};

/// The slot the library receives for one C++ named, for tests.
#[doc(hidden)]
#[must_use]
pub fn slot_back_for_test(slot: Slot) -> prolink_proto::Slot {
    convert::slot_back(slot)
}

/// A `TransferDone` event as the transfer path builds it, for tests.
#[doc(hidden)]
#[must_use]
pub fn transfer_done_for_test(id: u32, path: &str, failure: Option<&str>) -> Event {
    let mut event = convert::plain(EventKind::TransferDone, 0, 0);
    event.transfer = id;
    path.clone_into(&mut event.path);
    if let Some(reason) = failure {
        event.ok = false;
        reason.clone_into(&mut event.detail);
    }
    event
}

/// A player we have heard beats from but no status, for tests.
#[doc(hidden)]
#[must_use]
pub fn empty_player_for_test() -> Player {
    convert::player(&prolink::PlayerState {
        device: prolink::DeviceNumber::ONE,
        name: prolink::DeviceName::default(),
        beat: None,
        status: None,
    })
}

/// One browse row, for tests that cannot reach a deck.
///
/// The two live marks a server puts on a track row are the thing most worth
/// pinning, and a test cannot get one off the network on a build machine.
#[doc(hidden)]
#[must_use]
pub fn row_for_test(item: &prolink_proto::dbserver::MenuItem) -> Row {
    convert::row(item)
}
pub use anlz::read_anlz;
pub use pdb::{read_pdb, read_pdb_bytes};
pub use session::{default_config, interfaces, open};
